"""
Integration Test Generator - Auto-generates integration tests from CallGraph call paths.

Template-based (NO LLM) generation for speed and reliability.
Uses CallGraph.compute_call_paths() to find paths that pass through modified
code. Each path becomes one integration test class.

Supports Python (pytest + unittest.mock). Spring, Flask, FastAPI, and Django
API endpoint detection with framework-specific test stubs.

Usage:
    from integration_test_generator import generate_integration_tests

Python 3.8+ compatible. ASCII-only (cp1252-safe).
"""

import re
from pathlib import Path

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

MAX_PATHS = 20  # hard cap on paths per test file

# Heuristic keywords for API endpoint detection
_API_METHOD_KEYWORDS = {"get", "post", "put", "delete", "patch", "handle", "route"}
_API_CLASS_KEYWORDS = {"view", "controller", "handler", "resource", "router"}

# HTTP-verb prefixes in method names (Flask, Django, etc.)
_HTTP_VERB_PREFIXES = ("get_", "post_", "put_", "delete_", "patch_", "do_get", "do_post")

# ---------------------------------------------------------------------------
# Template strings - Python integration test output
# ---------------------------------------------------------------------------

_INT_FILE_HEADER = '''\
"""Integration tests - Auto-generated from CallGraph call paths.

Generated by integration_test_generator.py - review and complete as needed.
Each test class corresponds to one call path through the codebase.
"""
import pytest
from unittest.mock import patch, MagicMock
'''

_INT_CLASS_HEADER = '''\

class TestIntegration_{path_id}:
    """{doc}"""
'''

_INT_FULL_PATH_TEST = """\
    def test_full_path_executes(self):
        # Entry point: {entry_import}
        from {module} import {class_name}
        obj = {class_name}()
        # Call entry method with placeholder args; adjust as needed
        try:
            result = obj.{entry_method}({test_input})
            assert result is not None or result is None  # no unhandled exception
        except (TypeError, ValueError, AttributeError):
            pass  # acceptable for stub args
"""

_INT_FULL_PATH_TEST_NO_CLASS = """\
    def test_full_path_executes(self):
        # Entry point: {entry_import}
        from {module} import {entry_method}
        # Call entry function with placeholder args; adjust as needed
        try:
            result = {entry_method}({test_input})
            assert result is not None or result is None
        except (TypeError, ValueError, AttributeError):
            pass
"""

_INT_INTERMEDIATE_TEST = '''\
    def test_intermediate_called_{safe_method}(self):
        """Verify {intermediate_fqn} is invoked along the path."""
        with patch("{patch_target}") as mock_method:
            mock_method.return_value = MagicMock()
            from {module} import {class_name}
            obj = {class_name}()
            try:
                obj.{entry_method}({test_input})
            except Exception:
                pass  # focus is on mock assertion
            # Intermediate method should have been called
            # mock_method.assert_called()  # uncomment after supplying real args
'''

_INT_INTERMEDIATE_TEST_NO_CLASS = '''\
    def test_intermediate_called_{safe_method}(self):
        """Verify {intermediate_fqn} is invoked along the path."""
        with patch("{patch_target}") as mock_method:
            mock_method.return_value = MagicMock()
            from {module} import {entry_method}
            try:
                {entry_method}({test_input})
            except Exception:
                pass
            # mock_method.assert_called()  # uncomment after supplying real args
'''

# ---------------------------------------------------------------------------
# API endpoint test templates
# ---------------------------------------------------------------------------

_FLASK_API_TEST = '''\
    def test_api_endpoint_{safe_name}(self):
        """Flask endpoint test for {endpoint_method}."""
        # Assumes `app` is a Flask application fixture or import
        # from myapp import app as flask_app
        # client = flask_app.test_client()
        # response = client.get('/your-route')  # adjust method and route
        # assert response.status_code == 200
        pass  # TODO: configure Flask test client and route
'''

_FASTAPI_API_TEST = '''\
    def test_api_endpoint_{safe_name}(self):
        """FastAPI endpoint test for {endpoint_method}."""
        # from fastapi.testclient import TestClient
        # from myapp.main import app
        # client = TestClient(app)
        # response = client.get('/your-route')  # adjust method and route
        # assert response.status_code == 200
        pass  # TODO: configure FastAPI TestClient and route
'''

_DJANGO_API_TEST = '''\
    def test_api_endpoint_{safe_name}(self):
        """Django endpoint test for {endpoint_method}."""
        # from django.test import Client
        # client = Client()
        # response = client.get('/your-route/')  # adjust method and route
        # assert response.status_code == 200
        pass  # TODO: configure Django test Client and route
'''

_SPRING_API_TEST = '''\
    def test_api_endpoint_{safe_name}(self):
        """Spring MockMvc stub for {endpoint_method} (Python placeholder)."""
        # This is a Python stub. For actual Spring tests use:
        # mockMvc.perform(get("/your-route")).andExpect(status().isOk())
        pass  # TODO: implement in Java/Kotlin with MockMvc
'''

_GENERIC_API_TEST = '''\
    def test_api_endpoint_{safe_name}(self):
        """Generic HTTP endpoint test for {endpoint_method}."""
        # Adjust to your HTTP testing library (requests, httpx, etc.)
        pass  # TODO: call your test HTTP client here
'''

# ---------------------------------------------------------------------------
# Helper utilities
# ---------------------------------------------------------------------------


def _fqn_to_module_and_class(fqn):
    """Split a FQN like 'path/module.py::ClassName.method' into parts.

    Returns:
        (module_import, class_name, method_name)
        module_import: dotted import path derived from file path
        class_name:    simple class name or None
        method_name:   simple method name
    """
    if "::" not in fqn:
        # Bare name with no file context
        return ("", None, fqn)

    file_part, rest = fqn.split("::", 1)

    # Convert file path to importable module dotted string
    module_import = _file_path_to_module(file_part)

    # rest may be 'ClassName.method' or just 'function_name'
    if "." in rest:
        parts = rest.rsplit(".", 1)
        class_name = parts[0]
        method_name = parts[1]
    else:
        class_name = None
        method_name = rest

    return module_import, class_name, method_name


def _file_path_to_module(file_path):
    """Convert a file path like 'langgraph_engine/foo.py' to
    an importable dotted module name 'langgraph_engine.foo'.

    Handles forward and backslashes.
    """
    p = file_path.replace("\\", "/").rstrip("/")
    # Strip leading './' if present
    if p.startswith("./"):
        p = p[2:]
    # Remove .py extension
    if p.endswith(".py"):
        p = p[:-3]
    # Replace separators with dots
    module = p.replace("/", ".")
    return module


def _safe_identifier(name):
    """Convert any string to a safe Python identifier fragment."""
    cleaned = re.sub(r"[^a-zA-Z0-9_]", "_", str(name))
    # Collapse repeated underscores
    cleaned = re.sub(r"_+", "_", cleaned)
    return cleaned.strip("_") or "item"


def _build_patch_target(module_import, class_name, method_name):
    """Build the dotted patch target for unittest.mock.patch."""
    if not module_import:
        if class_name:
            return "%s.%s" % (class_name, method_name)
        return method_name
    if class_name:
        return "%s.%s.%s" % (module_import, class_name, method_name)
    return "%s.%s" % (module_import, method_name)


def _default_test_input(params_list):
    """Generate a comma-separated placeholder arg string for the given params."""
    if not params_list:
        return ""
    args = []
    for p in params_list:
        pname = str(p).split(":")[0].strip()
        args.append("None  # TODO: %s" % pname)
    return ", ".join(args)


# ---------------------------------------------------------------------------
# 1. detect_api_endpoints
# ---------------------------------------------------------------------------


def detect_api_endpoints(call_graph_snapshot):
    """Find method FQNs that look like HTTP API endpoints.

    Heuristics applied in order:
    1. Method name contains any of: get, post, put, delete, patch, handle, route
    2. Parent class name contains any of: View, Controller, Handler, Resource, Router
    3. Method has 'request' in its param list

    Args:
        call_graph_snapshot: A CallGraph instance (has .methods dict) or a dict
                             with a 'nodes' key (list of node dicts).

    Returns:
        list of str: Method FQNs that appear to be API endpoints.
    """
    endpoints = []
    try:
        methods_iter = _iter_methods(call_graph_snapshot)
        for node in methods_iter:
            fqn = node.get("id", "")
            name = node.get("name", "").lower()
            parent_class = str(node.get("parent_class", "") or "").lower()
            params = [str(p).lower() for p in (node.get("params") or [])]

            is_endpoint = False

            # Heuristic 1: method name keyword
            if any(kw in name for kw in _API_METHOD_KEYWORDS):
                is_endpoint = True

            # Heuristic 2: class name keyword
            if not is_endpoint:
                for kw in _API_CLASS_KEYWORDS:
                    if kw in parent_class:
                        is_endpoint = True
                        break

            # Heuristic 3: 'request' param
            if not is_endpoint:
                if any("request" in p for p in params):
                    is_endpoint = True

            if is_endpoint and fqn:
                endpoints.append(fqn)

    except Exception:
        pass

    return endpoints


# ---------------------------------------------------------------------------
# 2. find_affected_paths
# ---------------------------------------------------------------------------


def find_affected_paths(call_graph_snapshot, modified_files):
    """Find call paths that pass through any modified file.

    Args:
        call_graph_snapshot: A CallGraph instance whose compute_call_paths()
                             returns list of path dicts, or a dict with a
                             'call_paths' key.
        modified_files:      Iterable of file path strings (str or Path).

    Returns:
        list of path dicts (up to MAX_PATHS) where at least one node in
        path["path"] belongs to one of the modified files.
    """
    affected = []
    try:
        modified_set = _normalize_file_set(modified_files)
        if not modified_set:
            return affected

        paths = _get_call_paths(call_graph_snapshot)

        for path_dict in paths:
            if len(affected) >= MAX_PATHS:
                break
            node_fqns = path_dict.get("path", [])
            for fqn in node_fqns:
                if _fqn_belongs_to_files(fqn, modified_set):
                    affected.append(path_dict)
                    break

    except Exception:
        pass

    return affected


# ---------------------------------------------------------------------------
# 3. generate_path_test
# ---------------------------------------------------------------------------


def generate_path_test(path, methods_data):
    """Generate a single integration test class for one call path.

    Args:
        path:         Path dict: {"id": str, "path": [fqn, ...],
                                  "depth": int, "total_complexity": int}
        methods_data: Dict of FQN -> method node dict (from call graph).
                      Used to look up params, class names etc.

    Returns:
        str: Python test class source code.
    """
    try:
        path_id = _safe_identifier(path.get("id", "path_0"))
        node_fqns = path.get("path", [])

        if not node_fqns:
            return ""

        entry_fqn = node_fqns[0]
        entry_module, entry_class, entry_method = _fqn_to_module_and_class(entry_fqn)

        # Build human-readable path label for docstring
        labels = []
        for fqn in node_fqns[:5]:  # limit label length
            _, cls, mth = _fqn_to_module_and_class(fqn)
            if cls:
                labels.append("%s.%s" % (cls, mth))
            else:
                labels.append(mth)
        ellipsis = " -> ..." if len(node_fqns) > 5 else ""
        doc = "Tests call path: %s%s" % (" -> ".join(labels), ellipsis)

        # Lookup entry method params
        entry_node = methods_data.get(entry_fqn, {})
        entry_params = entry_node.get("params", []) if entry_node else []
        test_input = _default_test_input(entry_params)

        lines = []
        lines.append(_INT_CLASS_HEADER.format(path_id=path_id, doc=doc))

        # --- test_full_path_executes ---
        if entry_class:
            lines.append(
                _INT_FULL_PATH_TEST.format(
                    entry_import="%s.%s" % (entry_module, entry_class) if entry_module else entry_class,
                    module=entry_module or entry_class,
                    class_name=entry_class,
                    entry_method=entry_method,
                    test_input=test_input,
                )
            )
        else:
            lines.append(
                _INT_FULL_PATH_TEST_NO_CLASS.format(
                    entry_import="%s.%s" % (entry_module, entry_method) if entry_module else entry_method,
                    module=entry_module or "__main__",
                    entry_method=entry_method,
                    test_input=test_input,
                )
            )

        # --- test_intermediate_called_* for nodes 1..N-1 ---
        for inter_fqn in node_fqns[1:]:
            inter_module, inter_class, inter_method = _fqn_to_module_and_class(inter_fqn)
            safe_mth = _safe_identifier(inter_method)
            patch_target = _build_patch_target(inter_module, inter_class, inter_method)

            if entry_class:
                lines.append(
                    _INT_INTERMEDIATE_TEST.format(
                        safe_method=safe_mth,
                        intermediate_fqn=inter_fqn,
                        patch_target=patch_target,
                        module=entry_module or entry_class,
                        class_name=entry_class,
                        entry_method=entry_method,
                        test_input=test_input,
                    )
                )
            else:
                lines.append(
                    _INT_INTERMEDIATE_TEST_NO_CLASS.format(
                        safe_method=safe_mth,
                        intermediate_fqn=inter_fqn,
                        patch_target=patch_target,
                        module=entry_module or "__main__",
                        entry_method=entry_method,
                        test_input=test_input,
                    )
                )

        return "".join(lines)

    except Exception:
        return ""


# ---------------------------------------------------------------------------
# 4. generate_api_test
# ---------------------------------------------------------------------------


def generate_api_test(endpoint_method, framework="flask"):
    """Generate an API endpoint test stub for a single endpoint FQN.

    Args:
        endpoint_method: FQN of the endpoint method.
        framework:       One of 'flask', 'fastapi', 'django', 'spring',
                         or any other string (generic stub).

    Returns:
        str: Test method source code, or None if endpoint_method is empty.
    """
    if not endpoint_method:
        return None

    try:
        _, _, method_name = _fqn_to_module_and_class(endpoint_method)
        safe_name = _safe_identifier(method_name)
        fw = (framework or "").lower()

        if fw == "flask":
            return _FLASK_API_TEST.format(safe_name=safe_name, endpoint_method=endpoint_method)
        elif fw == "fastapi":
            return _FASTAPI_API_TEST.format(safe_name=safe_name, endpoint_method=endpoint_method)
        elif fw == "django":
            return _DJANGO_API_TEST.format(safe_name=safe_name, endpoint_method=endpoint_method)
        elif fw == "spring":
            return _SPRING_API_TEST.format(safe_name=safe_name, endpoint_method=endpoint_method)
        else:
            return _GENERIC_API_TEST.format(safe_name=safe_name, endpoint_method=endpoint_method)

    except Exception:
        return None


# ---------------------------------------------------------------------------
# 5. generate_integration_tests  (primary entry point)
# ---------------------------------------------------------------------------


def generate_integration_tests(project_root, modified_files, call_graph=None):
    """Generate integration tests based on call paths through modified files.

    Uses CallGraph.compute_call_paths() to find paths that pass through
    modified code. Each path becomes an integration test class.

    Args:
        project_root:   Root directory of the project (str or Path).
        modified_files: Iterable of file paths that were modified (str or Path).
        call_graph:     Optional CallGraph instance (or dict with 'call_paths').
                        When None the function returns an empty result dict.

    Returns:
        dict with keys:
            test_file_path  (str)  - where the integration test file should be written
            test_code       (str)  - generated pytest source code
            paths_tested    (int)  - number of call paths that generated tests
            methods_covered (int)  - total distinct method FQNs across all tested paths
    """
    empty = {
        "test_file_path": "",
        "test_code": "",
        "paths_tested": 0,
        "methods_covered": 0,
    }

    try:
        if call_graph is None:
            return empty

        root = Path(str(project_root))

        # Resolve affected call paths
        affected = find_affected_paths(call_graph, modified_files)
        if not affected:
            return empty

        # Build a methods lookup dict for param resolution
        methods_data = _build_methods_lookup(call_graph)

        # Determine output file path
        test_file_path = _resolve_test_file_path(root, modified_files)

        # Build test code
        code_parts = [_INT_FILE_HEADER]
        covered_fqns = set()

        for path_dict in affected:
            test_class = generate_path_test(path_dict, methods_data)
            if test_class and test_class.strip():
                code_parts.append(test_class)
                for fqn in path_dict.get("path", []):
                    covered_fqns.add(fqn)

        test_code = "\n".join(code_parts)

        return {
            "test_file_path": test_file_path,
            "test_code": test_code,
            "paths_tested": len(affected),
            "methods_covered": len(covered_fqns),
        }

    except Exception:
        return empty


# ---------------------------------------------------------------------------
# 6. write_integration_tests
# ---------------------------------------------------------------------------


def write_integration_tests(project_root, test_result, dry_run=False):
    """Write or preview the generated integration test file.

    Args:
        project_root: Root directory of the project (str or Path).
        test_result:  Dict returned by generate_integration_tests().
        dry_run:      If True, returns the path without writing to disk.

    Returns:
        str: Path of the file written (or that would be written), or ""
             if there was nothing to write.
    """
    try:
        test_file_path = test_result.get("test_file_path", "")
        test_code = test_result.get("test_code", "")

        if not test_file_path or not test_code.strip():
            return ""

        if not dry_run:
            dest = Path(str(test_file_path))
            dest.parent.mkdir(parents=True, exist_ok=True)
            dest.write_text(test_code, encoding="utf-8")

        return test_file_path

    except Exception:
        return ""


# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------


def _iter_methods(call_graph_snapshot):
    """Yield method node dicts from either a CallGraph instance or a snapshot dict."""
    if hasattr(call_graph_snapshot, "methods"):
        # CallGraph instance: .methods is a dict FQN -> node
        yield from call_graph_snapshot.methods.values()
        return

    # Dict snapshot: may have 'nodes' as list or as {'methods': [...], 'classes': [...]}
    if isinstance(call_graph_snapshot, dict):
        nodes = call_graph_snapshot.get("nodes", [])
        if isinstance(nodes, list):
            for n in nodes:
                if n.get("type") in ("method", "function"):
                    yield n
        elif isinstance(nodes, dict):
            for n in nodes.get("methods", []):
                yield n
    return


def _get_call_paths(call_graph_snapshot):
    """Return call paths from a CallGraph instance or snapshot dict."""
    if hasattr(call_graph_snapshot, "compute_call_paths"):
        return call_graph_snapshot.compute_call_paths() or []

    if isinstance(call_graph_snapshot, dict):
        return call_graph_snapshot.get("call_paths", []) or []

    return []


def _build_methods_lookup(call_graph_snapshot):
    """Build a FQN -> method node dict for param lookups."""
    result = {}
    try:
        if hasattr(call_graph_snapshot, "methods"):
            return dict(call_graph_snapshot.methods)
        for node in _iter_methods(call_graph_snapshot):
            fqn = node.get("id", "")
            if fqn:
                result[fqn] = node
    except Exception:
        pass
    return result


def _normalize_file_set(modified_files):
    """Normalize modified file paths to a set of forward-slash strings."""
    normalized = set()
    try:
        for f in modified_files or []:
            s = str(f).replace("\\", "/")
            normalized.add(s)
            # Also add just the basename for loose matching
            normalized.add(Path(s).name)
    except Exception:
        pass
    return normalized


def _fqn_belongs_to_files(fqn, file_set):
    """Check whether a FQN's file portion matches any entry in file_set."""
    if not fqn or "::" not in fqn:
        return False
    fqn_file = fqn.split("::")[0].replace("\\", "/")
    for f in file_set:
        if fqn_file == f or fqn_file.endswith("/" + f) or f.endswith("/" + fqn_file):
            return True
        # Match by basename alone
        if Path(fqn_file).name == f or Path(fqn_file).name == Path(f).name:
            return True
    return False


def _resolve_test_file_path(project_root, modified_files):
    """Determine the integration test file path based on modified files.

    Convention: tests/integration/test_integration_<stem>.py
    If multiple files are modified, uses 'modified' as the stem.
    """
    try:
        files = [str(f) for f in (modified_files or []) if f]
        if len(files) == 1:
            stem = Path(files[0]).stem
        elif files:
            stem = "modified"
        else:
            stem = "integration"

        return str(project_root / "tests" / "integration" / ("test_integration_%s.py" % stem))
    except Exception:
        return str(project_root / "tests" / "integration" / "test_integration.py")
