"""
REMOVED (v1.15.0) -- Step 5: Skill & Agent Selection

This module was removed as dead code. The orchestration prompt generated by
prompt-gen-expert (Step 0, Phase 1) already contains full skill and agent
selection. No runtime hardcoding or validation is needed.

If you see this file being imported, that import is stale and should be removed.
"""

raise ImportError(
    "step5_skill_agent_selection is removed (v1.15.0). "
    "Skill/agent selection is handled by the orchestration prompt in Step 0."
)
